CREATE SCHEMA IF NOT EXISTS SA;

DROP TABLE IF EXISTS SA.TOURLIST;

CREATE TABLE IF NOT EXISTS SA.TOURLIST
(TOUR_ID identity,
 NAME VARCHAR,
 DESCRIPTION VARCHAR,
 LOCATION VARCHAR,
 START_DATE DATE,
 END_DATE DATE,
 COUNT_LIMIT NUMBER
);

INSERT INTO SA.TOURLIST (NAME,DESCRIPTION,LOCATION,START_DATE,END_DATE,COUNT_LIMIT) VALUES ('TOUR1', 'DESC1', 'RUSSIA', to_date('01.01.2019', 'dd.mm.yyyy'), to_date('14.01.2019', 'dd.mm.yyyy'),100);
INSERT INTO SA.TOURLIST (NAME,DESCRIPTION,LOCATION,START_DATE,END_DATE,COUNT_LIMIT) VALUES ('TOUR2', 'DESC2', 'USA', to_date('01.02.2019', 'dd.mm.yyyy'), to_date('14.02.2019', 'dd.mm.yyyy'),2);
INSERT INTO SA.TOURLIST (NAME,DESCRIPTION,LOCATION,START_DATE,END_DATE,COUNT_LIMIT) VALUES ('TOUR3', 'DESC3', 'ITALY', to_date('01.03.2019', 'dd.mm.yyyy'), to_date('14.03.2019', 'dd.mm.yyyy'),3);


DROP TABLE IF EXISTS SA.USERLIST;
CREATE TABLE IF NOT EXISTS SA.USERLIST
(USER_ID identity,
 FIRST_NAME VARCHAR,
 LAST_NAME VARCHAR,
 EMAIL VARCHAR,
 PASSWORD VARCHAR,
 active boolean,
 birthday date
);

INSERT INTO SA.USERLIST (FIRST_NAME, LAST_NAME, EMAIL, PASSWORD, active, birthday ) values('IVAN', 'IVANOV', 'IVANOV@YA.RU', '1', true, to_date('01.02.2000', 'dd.mm.yyyy'));
INSERT INTO SA.USERLIST (FIRST_NAME, LAST_NAME, EMAIL, PASSWORD, active, birthday ) values('PETR', 'PETROV', 'PETROV@YA.RU', '2', false, to_date('01.02.2001', 'dd.mm.yyyy'));
INSERT INTO SA.USERLIST (FIRST_NAME, LAST_NAME, EMAIL, PASSWORD, active, birthday ) values('ALEX', 'ALEX', 'ALEX@YA.RU', '3', true, to_date('01.02.2003', 'dd.mm.yyyy'));


DROP TABLE IF EXISTS SA.ORDERLIST;
CREATE TABLE IF NOT EXISTS SA.ORDERLIST
(ORDER_ID identity,
 USER_ID NUMBER,
 USER_NAME VARCHAR,
 TOUR_ID NUMBER,
 TOUR_NAME VARCHAR,
 CONFIRMED BOOLEAN,
 TIME_KEY TIMESTAMP
);

