CREATE SCHEMA IF NOT EXISTS SA;

DROP TABLE IF EXISTS SA.TOURLIST;
CREATE TABLE IF NOT EXISTS SA.TOURLIST
(TOUR_ID identity,
 NAME VARCHAR(100),
 DESCRIPTION VARCHAR(100),
 LOCATION VARCHAR(100),
 START_DATE DATE,
 END_DATE DATE,
 COUNT_LIMIT NUMBER
);

INSERT INTO SA.TOURLIST (NAME,DESCRIPTION,LOCATION,START_DATE,END_DATE,COUNT_LIMIT) VALUES ('TRIP_1', 'AMAZING', 'RUSSIA', to_date('01.01.2019', 'dd.mm.yyyy'), to_date('14.01.2019', 'dd.mm.yyyy'),10);
INSERT INTO SA.TOURLIST (NAME,DESCRIPTION,LOCATION,START_DATE,END_DATE,COUNT_LIMIT) VALUES ('TRIP_2', 'WONDERFUL', 'UKRAINE', to_date('01.02.2019', 'dd.mm.yyyy'), to_date('14.02.2019', 'dd.mm.yyyy'),10);
INSERT INTO SA.TOURLIST (NAME,DESCRIPTION,LOCATION,START_DATE,END_DATE,COUNT_LIMIT) VALUES ('TRIP_3', 'AMAZING2', 'RUSSIA', to_date('01.03.2019', 'dd.mm.yyyy'), to_date('14.03.2019', 'dd.mm.yyyy'),10);

DROP TABLE IF EXISTS SA.USERLIST;
CREATE TABLE IF NOT EXISTS SA.USERLIST
(USER_ID identity,
 FIRST_NAME VARCHAR(100),
 LAST_NAME VARCHAR(100),
 EMAIL VARCHAR(100),
 PASSWORD VARCHAR(100),
 active boolean,
 birthday date
);


INSERT INTO SA.USERLIST (FIRST_NAME, LAST_NAME, EMAIL, PASSWORD, active, birthday ) values('IVAN', 'IVANOV', 'IVANOV@YA.RU', 'IVANOVIVAN', true, to_date('01.02.2000', 'dd.mm.yyyy'));
INSERT INTO SA.USERLIST (FIRST_NAME, LAST_NAME, EMAIL, PASSWORD, active, birthday ) values('PETR', 'PETROV', 'PETROV@YA.RU', 'PETRPETROV', false, to_date('01.02.2001', 'dd.mm.yyyy'));
INSERT INTO SA.USERLIST (FIRST_NAME, LAST_NAME, EMAIL, PASSWORD, active, birthday ) values('ALEX', 'ALEX', 'ALEX@YA.RU', 'ALEXALEX', true, to_date('01.02.2003', 'dd.mm.yyyy'));

DROP TABLE IF EXISTS SA.ORDERLIST;
CREATE TABLE IF NOT EXISTS SA.ORDERLIST
(ORDER_ID identity,
 USER_ID NUMBER,
 USER_NAME VARCHAR,
 TOUR_ID NUMBER,
 TOUR_NAME VARCHAR,
 CONFIRMED BOOLEAN,
 TIME_KEY TIMESTAMP
);

